stages:
  - test

test:
  stage: test
  image: python:3.12-slim
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - poetry update
    - poetry run coverage run -m unittest discover
    - poetry run coverage report -m
    - poetry run coverage xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
