[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "T. E. Kalayci"},
]
license = {text = "Apache-2.0"}
requires-python = "<4.0,>=3.12"
dependencies = [
    "flask<4.0,>=3.0",
    "flask-cors",
    "flask-openapi3[swagger]",
]
name = "uploader"
version = "0.1.0"
description = "A file uploader application"
readme = "README.md"
keywords = [
    "file",
    "upload",
    "download",
    "flask",
    "python",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
]

[project.urls]
homepage = "https://github.com/tekrei/file-uploader"
repository = "https://github.com/tekrei/file-uploader"
documentation = "https://github.com/tekrei/file-uploader"

[dependency-groups]
dev = [
    "autopep8",
    "coverage",
    "pyproject-parser[cli]",
]
