name: ci-python-unittest

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        #with:
        #  virtualenvs-create: false
      - name: Install dependencies
        run: poetry update
      - name: Test with unittest
        run: |
          poetry run coverage run -m unittest discover
          poetry run coverage report -m
          poetry run coverage xml
      - uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.xml
          minimum_coverage: 70